[general]
static=yes
writeprotect=no
clearglobalvars=no

[globals]

[default]
; 允许用户之间互相拨打
exten => _6XXX,1,NoOp(Dialed extension ${EXTEN})
same => n,Dial(SIP/${EXTEN},30)
same => n,Hangup()

; Echo 测试
exten => 7000,1,Answer()
same => n,Echo()
same => n,Hangup()

; 语音信箱
exten => 8000,1,Answer()
same => n,VoiceMail(${EXTEN}@default)
same => n,Hangup() 