@host = localhost:9501

### 1. Create Room
# @name createRoom
POST http://{{host}}/api/rooms
Content-Type: application/json

{
  "roomName": "Test Room",
  "userId": "user123",
  "config": {
    "maxParticipants": 10,
    "recordingEnabled": false
  }
}

### 2. Join Room
@roomId = {{createRoom.response.body.roomId}}
POST http://{{host}}/api/rooms/join
Content-Type: application/json

{
  "roomId": "{{roomId}}",
  "userId": "user123"
}

### 3. Leave Room
POST http://{{host}}/api/rooms/leave
Content-Type: application/json

{
  "roomId": "{{roomId}}",
  "userId": "user123"
}

### 4. SIP Call
POST http://{{host}}/api/rooms/sip
Content-Type: application/json
X-Conference-Room: 1234
X-Conference-Server: janus.example.com

{
  "roomId": "{{roomId}}"
}
